### ISSUE TITLE
最新版本需要手動下載嗎？

### ISSUE THREAD

**Issue by lazywei** [lotem/squirrel#47]
我在 rimeime.github.io/squirrel-update/ 看到的最新版本是 0.9.26.2
但是我用鼠鬚管的「檢查更新」時，他卻顯示 0.9.26.1 是最新版...
請問我有需要手動更新嗎？

感謝！　

![image](https://cloud.githubusercontent.com/assets/2840571/5690387/0aba73c8-98c1-11e4-9b13-1882d2f75298.png)

**Comment by lazywei** [comment]
手動下載 0.9.26.2 後一樣在檢查更新時會出現這個問題
我想也許是因爲這裏忘記改版本號了？
https://github.com/lotem/squirrel/blob/837864cb2b00a9c5514d500b36096b2d1f0fd5b2/update/appcast.xml#L14

**Comment by lotem** [comment]
是的，已是最新版。
兩個原因：
一是擔心連續推送新版本會令用家不快，所以 appcast 裏面特意把版本號寫爲 0.9.26.1，以免剛剛升級到這個版本的用家再受打擾。
二是……0.9.26.2 這個版本只修改了安裝程序，可能忘記 Rebuild，後來才發現 App 裏面的版本號不知怎的就沒變過來。

**Comment by lazywei** [comment]
瞭解！感謝！
